services:
  db_postgres_students:
    image: postgres
    container_name: db_postgres_students
    restart: always
    ports:
      - 1234:5432
    env_file:
      - .env.test

  student-selector-app:
    container_name: student-selector
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db_postgres_students
    env_file:
      - .env.test
